title:              AFIFA146
email:              afifafifa114@gmail.com
description:        >- # this means to ignore newlines until "baseurl:" An inarguably well-designed Jekyll theme.
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://github.com/AFIFA146/AFIFA146.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    AFIFA146
facebook_username:  Afifa
instagram_username: owp_fffa 
linkedin_username: afifa-231563364

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
